namespace Remembvoc.Models;

public enum Languages
{
    ARA,  // Arabic
    AFR,  // Afrikaans
    BEN,  // Bengali
    BEL,  // Belarusian
    BUL,  // Bulgarian
    CES,  // Czech
    CHN,  // Chinese
    DAN,  // Danish
    DEU,  // German
    ENG,  // English
    EST,  // Estonian
    ESP,  // Spanish
    FIL,  // Filipino
    FIN,  // Finnish
    FRA,  // French
    GRE,  // Greek
    HEB,  // Hebrew
    HIN,  // Hindi
    HRV,  // Croatian
    HUN,  // Hungarian
    IND,  // Indonesian
    ITA,  // Italian
    JPN,  // Japanese
    KOR,  // Korean
    LAT,  // Latvian
    LIT,  // Lithuanian
    MAL,  // Malay
    MAR,  // Marathi
    NLD,  // Dutch
    NOR,  // Norwegian
    POL,  // Polish
    POR,  // Portuguese
    PUN,  // Punjabi
    ROM,  // Romanian
    RUS,  // Russian
    SRP,  // Serbian
    SLO,  // Slovenian
    SLK,  // Slovak
    SWA,  // Swahili
    SWE,  // Swedish
    TAM,  // Tamil
    TEL,  // Telugu
    THA,  // Thai
    TUR,  // Turkish
    UDR,  // Urdu
    UKR,  // Ukrainian
    VIE,  // Vietnamese
    XHO,  // Xhosa
    ZUL   // Zulu
}