// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Remembvoc;

#nullable disable

namespace Remembvoc.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241025160050_AddedPrioritiesTable")]
    partial class AddedPrioritiesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1");

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Languages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortForm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShortForm")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Priorities", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutesToRepeat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Phrase")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Priorities", b =>
                {
                    b.HasOne("Remembvoc.Models.ApplicationModels.Words", "Words")
                        .WithOne("Priorities")
                        .HasForeignKey("Remembvoc.Models.ApplicationModels.Priorities", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Words", b =>
                {
                    b.HasOne("Remembvoc.Models.ApplicationModels.Languages", "Language")
                        .WithMany("Words")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Languages", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Remembvoc.Models.ApplicationModels.Words", b =>
                {
                    b.Navigation("Priorities")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
