// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Remembvoc.Infrastructure.Data;

#nullable disable

namespace Remembvoc.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.PriorityEntity", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutesToRepeat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.HasKey("WordId");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.WordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.PriorityEntity", b =>
                {
                    b.HasOne("Remembvoc.ApplicationCore.Common.Models.Entities.WordEntity", "Word")
                        .WithOne("Priority")
                        .HasForeignKey("Remembvoc.ApplicationCore.Common.Models.Entities.PriorityEntity", "WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.WordEntity", b =>
                {
                    b.HasOne("Remembvoc.ApplicationCore.Common.Models.Entities.LanguageEntity", "Language")
                        .WithMany("Words")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.LanguageEntity", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Remembvoc.ApplicationCore.Common.Models.Entities.WordEntity", b =>
                {
                    b.Navigation("Priority")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
